export const userConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGOUT: 'LOGOUT',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  VALIDATE_AUTH_TOKEN: 'VALIDATE_AUTH_TOKEN',
  VALIDATE_AUTH_TOKEN_SUCCESS: 'VALIDATE_AUTH_TOKEN_SUCCESS',
  VALIDATE_AUTH_TOKEN_FAILURE: 'VALIDATE_AUTH_TOKEN_FAILURE',

  USER_PROFILE: 'USER_PROFILE',
  USER_PROFILE_SUCCESS: 'USER_PROFILE_SUCCESS',
  USER_PROFILE_FAILURE: 'USER_PROFILE_FAILURE',

  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',

  VALIDATE_USERNAME: 'VALIDATE_USERNAME',
  VALIDATE_USERNAME_SUCCESS: 'VALIDATE_USERNAME_SUCCESS',
  VALIDATE_USERNAME_FAILURE: 'VALIDATE_USERNAME_FAILURE',

  USER_INVITE: 'USER_INVITE ',
  USER_INVITE_SUCCESS: 'USER_INVITE_SUCCESS',
  USER_INVITE_FAILURE: 'USER_INVITE_FAILURE',

  VALIDATE_USER_INVITE: 'VALIDATE_USER_INVITE ',
  VALIDATE_USER_INVITE_SUCCESS: 'VALIDATE_USER_INVITE_SUCCESS',
  VALIDATE_USER_INVITE_FAILURE: 'VALIDATE_USER_INVITE_FAILURE',

  SUBMIT_FEEDBACK: 'SUBMIT_FEEDBACK',
  SUBMIT_FEEDBACK_SUCCESS: 'SUBMIT_FEEDBACK_SUCCESS',
  SUBMIT_FEEDBACK_FAILURE: 'SUBMIT_FEEDBACK_FAILURE',

  ACTIVITY_STREAM: 'ACTIVITY_STREAM ',
  ACTIVITY_STREAM_SUCCESS: 'ACTIVITY_STREAM_SUCCESS',
  ACTIVITY_STREAM_FAILURE: 'ACTIVITY_STREAM_FAILURE',

  CLEAR_ALERT: 'CLEAR_ALERT',
};

export const labConstants = {
  LABS_ACTION_REQUEST: 'LABS_ACTION_REQUEST',
  LABS_ACTION_SUCCESS: 'LABS_ACTION_SUCCESS',
  LABS_ACTION_FAILURE: 'LABS_ACTION_FAILURE',
  FETCH_LABS_REQUEST: 'FETCH_LABS_REQUEST',
  FETCH_LABS_SUCCESS: 'FETCH_LABS_SUCCESS',
  FETCH_LABS_FAILURE: 'FETCH_LABS_FAILURE',
  LABS_DEFAULT: 'DEFAULT',
  LABS_ACCEPT: 'ACCEPT',
  LABS_REJECT: 'REJECT',
  LABS_JOIN: 'JOIN',
  GO_TO_LAB: 'GOTO_LAB',

  LAB_USERS: 'LAB_USERS ',
  LAB_USERS_SUCCESS: 'LAB_USERS_SUCCESS',
  LAB_USERS_FAILURE: 'LAB_USERS_FAILURE',

  RESEND_INVITATION: 'RESEND_INVITATION ',
  RESEND_INVITATION_SUCCESS: 'RESEND_INVITATION_SUCCESS',
  RESEND_INVITATION_FAILURE: 'RESEND_INVITATION_FAILURE',
  REFRESH: 'REFRESH',

  LAB_COLORS: [
    '#50368f',
    '#e94196',
    '#e0c3cd',
    '#186bad',
    '#38becc',
    '#98d7d2',
    '#28a489',
    '#a6cb58',
    '#b5db99',
    '#e32353',
    '#fec744',
    '#fedcbb',
    '#50368f',
    '#e94196',
    '#e0c3cd',
    '#186bad',
    '#38becc',
    '#98d7d2',
    '#28a489',
    '#a6cb58',
    '#b5db99',
    '#e32353',
    '#fec744',
    '#fedcbb',
  ],
};
